version: '3'
services:
  web:
    build: .
    environment:
      NODE_ENV: development
    command: bash -c "npx nodemon bin/www"
    volumes:
      - .:/home/node/express-mongo
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
     - "mongo-data:/data/db"
volumes:
  mongo-data:
